config/routes.rb
Rails.application.routes.draw do
  resources :pets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species,inclusion: {in: %w(dog cat rabbit)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show,:edit,:update,:destroy]
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    #get stuff from params
    #create new instance
    @pet = Pet.new(pet_params)
    if @pet.save
     redirect_to pets_path
    else
     render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name,:address,:species,:date_found)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :species, collection: %w(dog cat rabbit) %>
  <%= f.input :address %>
  <%= f.input :date_found %>
  <%= f.button :submit %>
<% end %>

app/views/pets/edit.html.erb
<%= render 'form' %>

app/views/pets/index.html.erb
<div class="container">
  <%= link_to new_pet_path do %>
  <button>
    New Pet
  </button>
  <% end %>
  <h1>Pets index</h1>
<% @pets.each do |pet| %>
   <p><%= link_to pet.name, pet_path(pet) %></p>
   <p><%= pet.species %></p>
   <p><%= pet.address %></p>
   <p><%= pet.date_found %></p>
<% end %>

</div>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<p><%= @pet.name %></p>
<p><%= @pet.species %></p>
<p><%= @pet.address %></p>
<p><%= @pet.date_found %></p>

<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to pet_path(@pet), method: :delete do %>
<button>DELETE</button>
<% end %>